### ISSUE TITLE
a suggestion

### ISSUE THREAD

**Issue by Stroketon** [Astral-Uploader/Server#3]
you want to save cost and have a enterprise level of storage go use digitalocean spaces its like 5 dollars per month xddd

**Comment by vanility0104** [comment]
xdddddddddddd

**Comment by Stroketon** [comment]
ok

**Comment by vanility0104** [comment]
same

**Comment by Stroketon** [comment]
and a other suggestion is to use joi

**Comment by Stroketon** [comment]
demote vanility from astral

**Comment by vanility0104** [comment]
why

**Comment by Autist69420** [comment]
yes

**Comment by Stroketon** [comment]
oh btw can you please stop using a lot of if and else just make them smaller

**Comment by Stroketon** [comment]
sometimes its pain in the ass to read parts of the astral's source

**Comment by Stroketon** [comment]
a example of my code `
router.post("/upload", authMiddleware(), schemaVaildation.query("schemaQuery", uploadSettingsSchema), upload.single("file"), async (req: apiRequest, res) => {
  if (!req.file) return res.status(400).json({
    success: false,
    message: "File is missing"
  });
  let { fakeUrl, showUrl } = req.query;

  let url = new urlClass(`${FILE_URL}/${req.fileName!}`);

  if (showUrl) url.showify();
  if (fakeUrl) url.fakeify(fakeUrl as string);

  res.json({ 
    success: true, 
    url: url.getUrl(),
    deletionUrl: `${process.env.BACKEND_URL}/files/${req.fileName}/delete?k=${req.deletionKey}` // temp until i found a better solution
  }); 
});
`
